# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - smartconnectionsensores

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://github.com/diegoamva/smartconneciontprod3.git/
        username: ${{ secrets.AzureAppService_ContainerUsername_987fcf077b4c4c448fc4ba62c8520aaa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e0801a6d06fa49cfb3dcdf9437bf51c4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: github.com/diegoamva/smartconneciontprod3.git/${{ secrets.AzureAppService_ContainerUsername_987fcf077b4c4c448fc4ba62c8520aaa }}/diegoamva/smartconneciontprod3.git/diegoamva/smartconneciontprod3.git/diegoamva/smartconneciontprod3/tree/masterhttps:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'smartconnectionsensores'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_08a98eec09854535911133676d3fe4f8 }}
        images: 'github.com/diegoamva/smartconneciontprod3.git/${{ secrets.AzureAppService_ContainerUsername_987fcf077b4c4c448fc4ba62c8520aaa }}/diegoamva/smartconneciontprod3.git/diegoamva/smartconneciontprod3.git/diegoamva/smartconneciontprod3/tree/masterhttps:${{ github.sha }}'